# Generated by Django 6.0.6 on 2026-07-27 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('snapshot_at', models.DateTimeField(db_index=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_full_snapshot', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=10)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('removed_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('make', models.CharField(db_index=True, max_length=100)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('mileage', models.PositiveIntegerField()),
                ('fuel', models.CharField(max_length=50)),
                ('transmission', models.CharField(blank=True, max_length=50)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'status'], name='listing_source_status_idx'), models.Index(fields=['make', 'model', 'year'], name='listing_vehicle_idx'), models.Index(fields=['source', 'last_seen_at'], name='listing_source_seen_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_listing_source_external_id')],
            },
        ),
        migrations.CreateModel(
            name='ListingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mileage', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='vehicles.importrun')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='vehicles.listing')),
            ],
            options={
                'ordering': ('-observed_at',),
                'indexes': [models.Index(fields=['listing', 'observed_at'], name='snapshot_listing_seen_idx')],
                'constraints': [models.UniqueConstraint(fields=('listing', 'import_run'), name='unique_listing_snapshot_per_import'), models.UniqueConstraint(fields=('listing', 'observed_at'), name='unique_listing_observed_at')],
            },
        ),
    ]
