# Generated by Django 6.0.6 on 2026-07-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_importrun_listing_listingsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('source', models.CharField(db_index=True, default='polovniautomobili', max_length=50)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('minimum_year', models.PositiveIntegerField()),
                ('maximum_year', models.PositiveIntegerField()),
                ('minimum_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel', models.CharField(blank=True, max_length=50)),
                ('transmission', models.CharField(blank=True, max_length=50)),
                ('source_search_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'pk'),
            },
        ),
    ]
