# Generated by Django 6.0.6 on 2026-07-27 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_marketprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='classification_confidence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='classification_manually_overridden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='classification_method',
            field=models.CharField(choices=[('source_data', 'Source data'), ('rule_based', 'Rule based'), ('manual', 'Manual'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='classification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='engine_family',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='facelift_status',
            field=models.CharField(choices=[('pre_facelift', 'Pre-facelift'), ('facelift', 'Facelift'), ('not_applicable', 'Not applicable'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='generation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='power_kw',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='transmission_category',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='marketprofile',
            name='engine_family',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='marketprofile',
            name='facelift_status',
            field=models.CharField(blank=True, choices=[('pre_facelift', 'Pre-facelift'), ('facelift', 'Facelift'), ('not_applicable', 'Not applicable'), ('unknown', 'Unknown')], max_length=20),
        ),
        migrations.AddField(
            model_name='marketprofile',
            name='generation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='marketprofile',
            name='maximum_power_kw',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketprofile',
            name='minimum_power_kw',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketprofile',
            name='maximum_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketprofile',
            name='minimum_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
