# Generated by Django 6.0.6 on 2026-07-27 18:04

import django.core.validators
import django.db.models.deletion
import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_listing_classification_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('source', models.CharField(default='polovniautomobili', max_length=50)),
                ('search_url', models.URLField(max_length=2000, validators=[vehicles.models.validate_polovni_search_url])),
                ('is_active', models.BooleanField(default=True)),
                ('maximum_pages', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)])),
                ('request_delay_seconds', models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('last_refresh_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_refresh_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_refresh_status', models.CharField(choices=[('never', 'Never run'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='never', max_length=10)),
                ('last_error_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SourceSearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=10)),
                ('result_pages_requested', models.PositiveIntegerField(default=0)),
                ('result_pages_completed', models.PositiveIntegerField(default=0)),
                ('advertisement_ids_discovered', models.PositiveIntegerField(default=0)),
                ('detail_records_completed', models.PositiveIntegerField(default=0)),
                ('listings_created', models.PositiveIntegerField(default=0)),
                ('listings_updated', models.PositiveIntegerField(default=0)),
                ('snapshots_created', models.PositiveIntegerField(default=0)),
                ('missing_advertisements_detected', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('source_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='vehicles.sourcesearch')),
            ],
            options={
                'ordering': ('-started_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='SourceSearchMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('is_currently_present', models.BooleanField(default=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_search_memberships', to='vehicles.listing')),
                ('source_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='vehicles.sourcesearch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_search', 'listing'), name='unique_source_search_listing_membership')],
            },
        ),
        migrations.CreateModel(
            name='SourceSearchRunListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_advertisement_url', models.URLField(max_length=2000)),
                ('detail_fetch_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_search_run_results', to='vehicles.listing')),
                ('source_search_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_results', to='vehicles.sourcesearchrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_search_run', 'listing'), name='unique_listing_per_source_search_run')],
            },
        ),
    ]
