# Generated by Django 6.0.6 on 2026-07-27 18:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def backfill_external_ids(apps, schema_editor):
    RunListing = apps.get_model("vehicles", "SourceSearchRunListing")
    for observation in RunListing.objects.select_related("listing"):
        observation.external_id = observation.listing.external_id
        observation.save(update_fields=("external_id",))


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_sourcesearch_sourcesearchrun_sourcesearchmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesearchrunlisting',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sourcesearch',
            name='maximum_pages',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='sourcesearch',
            name='request_delay_seconds',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='sourcesearchrunlisting',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_search_run_results', to='vehicles.listing'),
        ),
        migrations.RunPython(backfill_external_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sourcesearchrunlisting',
            name='external_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='sourcesearchrunlisting',
            constraint=models.UniqueConstraint(fields=('source_search_run', 'external_id'), name='unique_external_id_per_source_search_run'),
        ),
    ]
