# Generated by Django 6.0.6 on 2026-08-17 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_listing_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('api_url', models.URLField(max_length=2000)),
                ('api_token_env_var', models.CharField(blank=True, max_length=100)),
                ('price_bracket_size', models.PositiveIntegerField(default=5000)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_dealer_source_external_id')],
            },
        ),
        migrations.CreateModel(
            name='DealerInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=10)),
                ('inventory_count', models.PositiveIntegerField(default=0)),
                ('median_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dominant_price_bracket_low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dominant_price_bracket_high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dominant_price_bracket_count', models.PositiveIntegerField(default=0)),
                ('average_active_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disappeared_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='vehicles.dealer')),
            ],
            options={
                'ordering': ('-observed_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DealerSnapshotListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mileage', models.PositiveIntegerField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_inventory_items', to='vehicles.listing')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='vehicles.dealerinventorysnapshot')),
            ],
        ),
        migrations.AddField(
            model_name='dealerinventorysnapshot',
            name='listings',
            field=models.ManyToManyField(related_name='dealer_snapshots', through='vehicles.DealerSnapshotListing', to='vehicles.listing'),
        ),
        migrations.CreateModel(
            name='DealerListingMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('disappeared_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_currently_present', models.BooleanField(db_index=True, default=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_memberships', to='vehicles.dealer')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_memberships', to='vehicles.listing')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dealer', 'listing'), name='unique_dealer_listing_membership')],
            },
        ),
        migrations.AddConstraint(
            model_name='dealersnapshotlisting',
            constraint=models.UniqueConstraint(fields=('snapshot', 'listing'), name='unique_listing_per_dealer_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='dealerinventorysnapshot',
            constraint=models.UniqueConstraint(fields=('dealer', 'observed_at'), name='unique_dealer_snapshot_time'),
        ),
    ]
