# Generated by Django 6.0.6 on 2026-08-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_dealer_dealerinventorysnapshot_dealersnapshotlisting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerlistingmembership',
            name='is_relevant',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
