# Generated by Django 6.0.6 on 2026-08-17 20:14

from django.db import migrations, models


def backfill_captured_observations(apps, schema_editor):
    DealerSnapshotListing = apps.get_model('vehicles', 'DealerSnapshotListing')
    ListingSnapshot = apps.get_model('vehicles', 'ListingSnapshot')
    for item in DealerSnapshotListing.objects.select_related('snapshot').iterator():
        observation = ListingSnapshot.objects.filter(
            listing_id=item.listing_id,
            observed_at=item.snapshot.observed_at,
        ).first()
        item.observed_at = item.snapshot.observed_at
        item.raw_data = observation.raw_data if observation else None
        item.save(update_fields=('observed_at', 'raw_data'))


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_dealerlistingmembership_is_relevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealersnapshotlisting',
            name='observed_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dealersnapshotlisting',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealersnapshotlisting',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('removed', 'Removed'), ('unknown', 'Unknown')], default='active', max_length=10),
        ),
        migrations.RunPython(backfill_captured_observations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='dealersnapshotlisting',
            name='observed_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
