# Generated by Django 6.0.6 on 2026-08-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_alter_dealer_inventory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='is_qa',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
