# Generated by Django 6.0.6 on 2026-08-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_dealer_is_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerlistingmembership',
            name='description_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
