# Generated by Django 6.0.6 on 2026-08-26 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_dealerlistingmembership_description_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealersnapshotlisting',
            name='vin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='repeat_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='repeat_detection_method',
            field=models.CharField(blank=True, choices=[('vin', 'VIN match')], max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='repeated_listing_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeated_listings', to='vehicles.listing'),
        ),
        migrations.AddField(
            model_name='listing',
            name='vin',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='listingsnapshot',
            name='vin',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
