# Generated by Django 6.0.6 on 2026-08-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_dealersnapshotlisting_vin_listing_repeat_detected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='vin_checked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='vin_lookup_error',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
